// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Block = 3,
  BlockType = 4,
  BlockName = 5,
  Fields = 6,
  Field = 7,
  FieldName = 8,
  FieldType = 9,
  Constraints = 10,
  Constraint = 11
