// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "$tOYQPOOOOQO'#C`'#C`O_QPO'#C_QOQPOOOOQO'#Ca'#CaOdQPO,58yOiQPO1G.eOOQO'#Ch'#ChOiQPO7+$POOQO'#Cd'#CdOqQPO'#CcOOQO'#Ci'#CiOvQPO'#CbO!OQPO7+$POOQO-E6f-E6fO!TQPO<<GkOOQO'#Ce'#CeO!YQPO,58}OOQO-E6g-E6gOOQO<<Gk<<GkOOQOAN=VAN=VOOQO'#Cg'#CgOOQO'#Cj'#CjO!eQPO'#CfO!pQPO1G.iOOQO-E6h-E6hO!xQPO7+$TO!xQPO7+$TO#TQPO<<Go",
  stateData: "#`~OaOSPOS~ObPO~ObSO~OcUO~ObXOdVO~Ob`O~ObXOfUX~OfcO~OfdO~ObeOdYPeYP~ObeOdYXeYX~OdVOekO~OdVObVqfVq~OdVObVyfVy~O",
  goto: "!p_PPP`cfioty|!P!T!c!jRRORQORTQQ]UR_WVZUW[VYUW[RaYRhaTfagQWUU^WjlQjhRlkS[UWRb[QgaRig",
  nodeNames: "⚠ Comment Program Block BlockType BlockName Fields Field FieldName FieldType Constraints Constraint",
  maxTerm: 22,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "#R~RYXYqYZ!P[]qpqq|}!U!P!Q!Z!c!}!l#T#o!l#o#p!w#q#r!|~vRa~XYq[]qpqq~!UOd~~!ZOe~~!^P!P!Q!a~!fQP~OY!aZ~!a~!qQb~!c!}!l#T#o!l~!|Oc~~#ROf~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
