# Use postgres/example user/password credentials
version: '3.6'

services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: hiuDPEwsEQfGKnmeSHcuJQ==
            POSTGRES_DB: appdb
    graphql-engine:
        image: hasura/graphql-engine:v1.3.3
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - "postgres"
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:hiuDPEwsEQfGKnmeSHcuJQ==@postgres:5432/appdb
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    redisgraph:
        container_name: redisgraph
        image: redislabs/redisgraph
        ports:
            - 6379:6379
        volumes: 
            - ../redis-data:/data
        # https://github.com/RedisGraph/RedisGraph/issues/575#issuecomment-516896821
                # --loadmodule /usr/lib/redis/modules/redisgraph.so \
        command: redis-server --save 60 1 --loadmodule /usr/lib/redis/modules/redisgraph.so
volumes:
    postgres_data: