version: "3.9"
services: 
    redisgraph:
        container_name: redisgraph
        image: redislabs/redisgraph
        ports:
            - 6379:6379
        volumes: 
            - ../redis-data:/data
        # https://github.com/RedisGraph/RedisGraph/issues/575#issuecomment-516896821
                # --loadmodule /usr/lib/redis/modules/redisgraph.so \
        command: redis-server --save 60 1 --loadmodule /usr/lib/redis/modules/redisgraph.so